default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
test:
  <<: *default
  database: PortalSolarDevTest_test
development:
  <<: *default
  database: PortalSolarDevTest_development
production:
  <<: *default
  database: PortalSolarDevTest_production
  username: PortalSolarDevTest
  password: <%= ENV['PORTALSOLARDEVTEST_DATABASE_PASSWORD'] %>
